server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/user/callback/{registrationId}"
            scope: name, account_email, phone_number, gender, birthday, birthyear, gender
            client-authentication-method: client_secret_post
          naver:
            client-id: ${NAVER_REST_API_KEY}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/user/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

jwt:
  secret-key: ${SECRET_KEY}
